name: dbt CI

on:
  push:
    branches:
      - main  # You can change this to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Choose the Python version you need

    - name: Install dbt-bigquery
      run: |
        pip install dbt-bigquery
        dbt --version

    - name: Set up GCP credentials
      run: |
        echo "$GCP_SERVICE_ACCOUNT_KEY" | base64 -d > gcp-credentials.json
        gcloud auth activate-service-account --key-file=gcp-credentials.json --project="$GCP_PROJECT_ID"
        dbt debug  # Verify that the credentials are set up correctly

    - name: Run dbt test
      run: |
        dbt run --profiles-dir .dbt --target dev
        dbt test --profiles-dir .dbt --target dev
